{{- /*
# Template to create a POD Distruption Budget
*/ -}}
{{- define "common.pdb.tpl" -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
{{ template "common.metadata" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "common.name" . }}
      release: {{ .Release.Name | quote }}
      version: {{ .Values.version }}
{{- end -}}
{{- define "common.pdb" -}}
{{- template "common.util.merge" (append . "common.pdb.tpl") -}}
{{- end -}}